export const Types = {
    TEST_ACTION : 'TEST_ACTION',
    ITEMS_LIST: 'ITEMS_LIST', 
    HOME_PAGE : 'HOME_PAGE',
    DELETE_ITEMS : 'DELETE_ITEMS',
    EDIT_BOX_DETAILS : 'EDIT_BOX_DETAILS',
    FORM_ACTION_TYPE : 'FORM_ACTION_TYPE',
    BOX_ITEMS: "BOX_ITEMS",
    SEARCH_ITEMS : 'SEARCH_ITEMS',
}